name: t2v
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip=23.0.1
  - pytorch=2.0.0
  - pip:
    - accelerate==0.18.0
    - opencv-python-headless==4.5.1.48
    - streamlit==1.20.0
    - git+https://github.com/huggingface/diffusers.git
    - git+https://github.com/huggingface/transformers.git
